"""Plan schemas - What LLM generates as execution steps."""

from enum import Enum
from typing import Any, Dict, List
from pydantic import BaseModel, Field


class RiskLevel(str, Enum):
    LOW = "low"        # Read operations
    MEDIUM = "medium"  # Write with safeguards
    HIGH = "high"      # Destructive, needs confirmation


class PlanStep(BaseModel):
    """Single step in execution plan."""
    step_id: str
    tool: str                              # Tool to call
    params: Dict[str, Any] = Field(default_factory=dict)
    depends_on: List[str] = Field(default_factory=list)
    risk: RiskLevel = RiskLevel.LOW


class Plan(BaseModel):
    """Complete plan generated by planner."""
    task_id: str
    user_id: str
    steps: List[PlanStep]
    
    def get_step(self, step_id: str) -> PlanStep | None:
        return next((s for s in self.steps if s.step_id == step_id), None)
